name: Rebuild Feed and Deploy
on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:
permissions:
  contents: write
jobs:
  rebuild-and-deploy:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      DISABLE_SUMMARIES: ${{ secrets.DISABLE_SUMMARIES }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install deps (robust, no lock strictness)
        run: |
          npm install
          npm install -D tsx
      - name: Rebuild feed
        run: npx tsx scripts/rebuild.ts
      - name: Commit updated feed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          # Ensure paths exist so git add never fails
          mkdir -p public/data public/archive
          # Add whatever exists; ignore if empty
          git add public/data || true
          git add public/archive || true
          # Commit only if there are staged changes
          git diff --cached --quiet || git commit -m "chore: update feed $(date -u +'%Y-%m-%dT%H:%MZ')"
          # Push if we committed anything
          git rev-parse --verify HEAD >/dev/null 2>&1 && git push || true
      - name: Remove API routes for static export
        run: rm -rf app/api || true

      - name: "Build static site (output: export)"
        env:
          NEXT_TELEMETRY_DISABLED: '1'
        run: npm run build

      - name: Show out/ listing (debug)
        run: ls -la out || (echo "out/ missing!" && exit 1)

      - name: Deploy to GitHub Pages (gh-pages)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          publish_branch: gh-pages
